# Generated by Django 5.0.6 on 2024-07-02 11:50

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('userform', '0004_alter_user_email'),
    ]

    operations = [
        migrations.RenameField(
            model_name='user',
            old_name='email',
            new_name='mail',
        ),
    ]
