# Generated by Django 5.0.6 on 2024-07-02 11:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('userform', '0006_remove_user_mail_user_email_alter_user_name'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='email',
            field=models.EmailField(default='null', max_length=254),
        ),
    ]
